### ISSUE TITLE
The "MergeTask" failed unexpectedly. ...

### ISSUE THREAD

**Issue by Chadley08** [emerbrito/ILMerge-MSBuild-Task#11]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "MergeTask" task failed unexpectedly.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ILMerge.MsBuild.Task.MergeTask.MergeAssemblies(String mergerPath, MergerSettings settings) in D:\Dev\Github\ILMerge-MSBuild-Task\ILMerge.MSBuild.Task\ILMerge.MSBuild.Task\MergeTask.cs:line 313
   at ILMerge.MsBuild.Task.MergeTask.Execute() in D:\Dev\Github\ILMerge-MSBuild-Task\ILMerge.MSBuild.Task\ILMerge.MSBuild.Task\MergeTask.cs:line 162
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Modulus.API.Licensed			
```

Only changed the TargetFramework field in the .json file from null to v4.7.1. Otherwise I'm using the defaults and I get this error.

**Comment by emerbrito** [comment]
@Chadley08 It is being a while since you posted here. 
I apologize for the delay, I wasnt getting any notifications and since I didn't have anything to change on this project I wasn't visiting it... anyway:

Framework v4.7 didn't exist when this project was created - I believe. When trying to parse the configuration file it will fail if version is greater than 4.6.*

I will make the required changes. Assuming we don't have any unexpected behavior while merging 4.7 assemblies, nuget package should be updated soon.
