### ISSUE TITLE
Support for Xamarin.Android

### ISSUE THREAD

**Issue by sdejesusF** [emerbrito/ILMerge-MSBuild-Task#30]
Hi, 

does this package supports Xamarin.android? 

Im trying to merge the assemblies so I can then obfuscate them and tried this package but Im getting this error:
`Error		The "MergeTask" task failed unexpectedly.
System.ArgumentOutOfRangeException: Unable to parse .Net framework version: v9.0
Parameter name: version
   at ILMerge.MsBuild.Task.FrameworkInfo.ToILmergeTargetPlatform(String version, String architecture) in D:\Dev\Github\ILMerge-MSBuild-Task\ILMerge.MSBuild.Task\ILMerge.MSBuild.Task\FrameworkInfo.cs:line 122
   at ILMerge.MsBuild.Task.MergeTask.SetDefaults(MergerSettings settings) in D:\Dev\Github\ILMerge-MSBuild-Task\ILMerge.MSBuild.Task\ILMerge.MSBuild.Task\MergeTask.cs:line 250
   at ILMerge.MsBuild.Task.MergeTask.Execute() in D:\Dev\Github\ILMerge-MSBuild-Task\ILMerge.MSBuild.Task\ILMerge.MSBuild.Task\MergeTask.cs:line 136
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
`

**Comment by brcaswell** [comment]
It depends, does Xamarin.Android use v4.0 .NET Runtime?  Note that this is an MSBuild project for ILMerge (it extends it actually) - it doesn't add support for runtime platforms that ILMerge doesn't support.
